=== md5checksum/acume/IntelligentCache/src/main/resources/cubedefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.guavus.com/CubeDefinition" targetNamespace="http://www.guavus.com/CubeDefinition" elementFormDefault="qualified">
	<complexType name="ReferenceField">
		<sequence>
			<element name="String2Id" type="boolean" minOccurs="1" maxOccurs="1"/>
			<element name="String2IdTable" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="Type" type="tns:FieldType" minOccurs="1" maxOccurs="1"/>
			<element name="DataType" type="tns:FieldDataType" minOccurs="1" maxOccurs="1"/>
			<element name="ColumnWidth" type="int" minOccurs="0" maxOccurs="1"/>
			<element name="StaticValues" type="tns:StaticValuesList" minOccurs="0" maxOccurs="1"/>
		</sequence>
		<attribute name="FieldName" type="ID" use="required"/>
	</complexType>
	<complexType name="Field">
		<attribute name="Field" type="IDREF" use="required"/>
		<attribute name="Persist" type="boolean" use="optional"/>
		<attribute name="DefaultValue" type="string" use="optional"/>
	</complexType>
	<complexType name="IndexedField">
		<attribute name="Field" type="IDREF" use="required"/>
		<attribute name="Persist" type="boolean" use="optional"/>
		<attribute name="DefaultValue" type="string" use="optional"/>
		<attribute name="Index" type="int" use="required"/>
	</complexType>
	<complexType name="StaticValuesList">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="Value" type="string"/>
		</sequence>
	</complexType>
	<simpleType name="FieldDataType">
		<restriction base="string">
			<enumeration value="Bigint"/>
			<enumeration value="Char"/>
			<enumeration value="Date"/>
			<enumeration value="Datetime"/>
			<enumeration value="Decimal"/>
			<enumeration value="Double"/>
			<enumeration value="Float"/>
			<enumeration value="Int"/>
			<enumeration value="Smallint"/>
			<enumeration value="Tinyint"/>
			<enumeration value="Varchar"/>
			<enumeration value="Varbinary"/>
			<enumeration value="Blob"/>
		</restriction>
	</simpleType>
	<simpleType name="FieldType">
		<restriction base="string">
			<enumeration value="Router"/>
			<enumeration value="Pop"/>
			<enumeration value="AS"/>
			<enumeration value="RouterPath"/>
			<enumeration value="Url"/>
			<enumeration value="Subscriber"/>
			<enumeration value="Bytes"/>
			<enumeration value="Packets"/>
			<enumeration value="IPAddress"/>
			<enumeration value="ByteArray"/>
			<enumeration value="Generic"/>
			<enumeration value="Record"/>
		</restriction>
	</simpleType>
	<complexType name="Range">
		<attribute name="Name" type="string" use="required"/>
		<attribute name="Type" type="string" use="required"/>
		<attribute name="RangeStart" type="string" use="optional"/>
		<attribute name="RangeEnd" type="string" use="optional"/>
	</complexType>
	<complexType name="ReferenceMeasure">
		<sequence>
			<element name="Function" type="tns:MeasureFunction" minOccurs="1" maxOccurs="1"/>
			<element name="StorageMode" type="tns:MeasureStorageMode" minOccurs="0" maxOccurs="1"/>
			<element name="Field" type="tns:Field" minOccurs="1" maxOccurs="1"/>
			<element name="AuxiliaryField" type="tns:Field" minOccurs="0" maxOccurs="unbounded"/>
			<element name="Range" type="tns:Range" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="MeasureName" type="ID" use="required"/>
	</complexType>
	<complexType name="Measure">
		<attribute name="Measure" type="IDREF" use="required"/>
	</complexType>
	<complexType name="ReferenceFilter">
		<sequence>
			<element name="Condition" type="tns:FilterCondition"/>
			<element name="Expression" type="tns:FilterExpression" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="FilterName" type="ID" use="required"/>
	</complexType>
	<complexType name="Filter">
		<attribute name="Filter" type="IDREF" use="required"/>
	</complexType>
	<simpleType name="MeasureStorageMode">
		<restriction base="string">
			<enumeration value="Combinable"/>
			<enumeration value="NonCombinable"/>
			<enumeration value="MultiPartNonCombinable"/>
		</restriction>
	</simpleType>
	<simpleType name="MeasureFunction">
		<restriction base="string">
			<enumeration value="Summation"/>
			<enumeration value="Average"/>
			<enumeration value="Minimum"/>
			<enumeration value="Maximum"/>
			<enumeration value="Count"/>
			<enumeration value="Entropy"/>
			<enumeration value="HH"/>
			<enumeration value="PCSA"/>
			<enumeration value="CONC"/>
			<enumeration value="BloomFilter"/>
			<enumeration value="CPC"/>
			<enumeration value="AVS"/>
			<enumeration value="DenseVectorVer"/>
			<enumeration value="DenseVectorHor"/>
		</restriction>
	</simpleType>
<complexType name="ReferenceDimensionSet">
        <sequence>
            <element name="Type" type="tns:DimensionSetType" minOccurs="1" maxOccurs="1"/>
            <element name="Field" type="tns:Field" minOccurs="0" maxOccurs="unbounded"/>
            <element name="IndexedField" type="tns:IndexedField" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="DimensionSetName" type="ID" use="required"/>
        <attribute name="DimesionSetId" type="int" use="optional"/>
    </complexType>	
<complexType name="DimensionSet">
<attribute name="DimensionSet" type="IDREF" use="required"/>
	</complexType>
	<simpleType name="DimensionSetType">
		<restriction base="string">
			<enumeration value="Dynamic"/>
			<enumeration value="Static"/>
			<enumeration value="Hybrid"/>
		</restriction>
	</simpleType>
	<simpleType name="FieldOperator">
		<restriction base="string">
			<enumeration value="Equal"/>
			<enumeration value="NotEqual"/>
			<enumeration value="GreaterThan"/>
			<enumeration value="LessThan"/>
			<enumeration value="GreaterThanOrEqual"/>
			<enumeration value="LessThanOrEqual"/>
			<enumeration value="Between"/>
			<enumeration value="Like"/>
			<enumeration value="In"/>
		</restriction>
	</simpleType>
	<simpleType name="FilterCondition">
		<restriction base="string">
			<enumeration value="And"/>
			<enumeration value="Or"/>
			<enumeration value="None"/>
		</restriction>
	</simpleType>

	<complexType name="Cube">
		<sequence>
			<element name="Name" type="string"/>
			<element name="DimensionSet" type="tns:DimensionSet"/>
			<element name="Measure" type="tns:Measure"/>
			<element name="Filter" type="tns:Filter"/>
			<element name="BIUser" minOccurs="0" maxOccurs="1"/>
		</sequence>
        <attribute name="MFIndex" type="int" use="optional"/>
	</complexType>
	<complexType name="FilterExpression">
		<sequence>
			<element name="Field" type="tns:Field"/>
			<element name="Operator" type="tns:FieldOperator"/>
			<element name="Value" type="string"/>
		</sequence>
	</complexType>
	<simpleType name="BinType">
		<restriction base="string">
			<enumeration value="None"/>
			<enumeration value="SE"/>
			<enumeration value="DME"/>
		</restriction>
	</simpleType>
	<complexType name="Bin">
		<sequence>
			<element name="Name" type="string"/>
			<element name="BinType" type="tns:BinType"/>
			<element name="BinInterval" type="int" minOccurs="1" maxOccurs="1"/>
			<element name="AggregationInterval" type="int" minOccurs="0" maxOccurs="unbounded"/>
			<element name="FreezeInterval" type="int" minOccurs="1" maxOccurs="1"/>
			<element name="Cubes" type="tns:Cube" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
    <complexType name="ReferenceDataSource">
        <sequence>
            <element name="DataType" type="string"/>
            <element name="AdaptorName" type="string"/>
            <element name="DataInterval" type="int" minOccurs="1" maxOccurs="1" default="300"/>
        </sequence>
			<attribute name="DataSourceName" type="ID" use="required"/>
    </complexType>
    <complexType name="DataSource">
        <attribute name="DataSource" type="IDREF" use="required"/>
	</complexType>

    <complexType name ="RecordSet">
        <sequence>
        <element name="Name" type="string"/>
        <element name="MaxRecordCount" type="int" minOccurs="0" maxOccurs="1" default="10000"/>
        <element name="TruncateFlag" type="int" minOccurs="0" maxOccurs="1" default="0"/>
        <element name="Periodicity" type="int" minOccurs="0" maxOccurs="1" default="5"/>
        <element name="RecordSetBatchSize" type="int" minOccurs="0" maxOccurs="1" default="50"/>
        <element name="Caching" type="boolean" minOccurs="0" maxOccurs="1"/>
        <element name="DataSource" type="tns:DataSource" minOccurs="0" maxOccurs="1"/>
		<element name="Field" type="tns:Field" minOccurs="1" maxOccurs="unbounded"/>
		<element name="EEField" type="tns:Field" minOccurs="0" maxOccurs="unbounded"/>
        <element name="TSField" type="tns:Field" minOccurs="1" maxOccurs="1" />
        <element name="KeyField" type="tns:Field" minOccurs="0" maxOccurs="unbounded" />
        <element name="Filter" type="tns:Filter" minOccurs="0" maxOccurs="1"/>
        </sequence>
    </complexType>
	<complexType name="CubeContainer">
		<sequence>
			<element name="RefField" type="tns:ReferenceField" minOccurs="1" maxOccurs="unbounded"/>
			<element name="RefMeasure" type="tns:ReferenceMeasure" minOccurs="1" maxOccurs="unbounded"/>
			<element name="RefFilter" type="tns:ReferenceFilter" minOccurs="1" maxOccurs="unbounded"/>
            <element name="RefDimensionSet" type="tns:ReferenceDimensionSet" minOccurs="1" maxOccurs="unbounded"/>
			<element name="Bins" type="tns:Bin" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
    <complexType name="RecordContainer">
        <sequence>
			<element name="RefField" type="tns:ReferenceField" minOccurs="1" maxOccurs="unbounded"/>
            <element name="RefFilter" type="tns:ReferenceFilter" minOccurs="0" maxOccurs="unbounded"/>
            <element name="RefData" type="tns:ReferenceDataSource" minOccurs="0" maxOccurs="unbounded"/>
            <element name="RecordSet" type="tns:RecordSet" minOccurs="1" maxOccurs="unbounded"/>
            <element name="Version" type="string" default="1.0" minOccurs="0" maxOccurs="1"/>
        </sequence>
    </complexType>

    
    <simpleType name="StringId">
        <restriction base="integer">
            <minInclusive value="0"/>
            <maxInclusive value="1000000"/>
        </restriction>
    </simpleType>


    <simpleType name="StringWidth">
        <restriction base="integer">
            <minInclusive value="8"/>
            <maxInclusive value="512"/>
        </restriction>
    </simpleType>


    
    <complexType name="StringIdMapEntry">
        <sequence>
            <element name="String" type="string" minOccurs="1" maxOccurs="1"/>
            <element name="Id" type="tns:StringId" minOccurs="0" maxOccurs="1" />
        </sequence>
    </complexType>  

    <complexType name="StringNameType">
        <sequence>
            <element name="Name" type="string" minOccurs="1" maxOccurs="1"/>    
            <element name="StringNameWidth" type="tns:StringWidth" minOccurs="0" maxOccurs="1"/>    
            <element name="FixedStringIds" type="tns:StringIdMapEntry" minOccurs="0" maxOccurs="unbounded" />  
            <element name="BIUser" minOccurs="0" maxOccurs="1"/> 
        </sequence>
    </complexType>

    <complexType name="StringNameTypeContainer">
        <sequence>
            <element name="StringNameTypes" type="tns:StringNameType" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

	<element name="CubeDef" type="tns:CubeContainer"/>
    <element name="RecordDef" type="tns:RecordContainer"/>
    <element name="StringNameTypeDef" type="tns:StringNameTypeContainer"/>
</schema>

=== md5checksum/acume/cache/src/test/resources/muralinstacubedefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:CubeDef xsi:schemaLocation="http://www.guavus.com/CubeDefinition CubeDefinition.xsd" xmlns:tns="http://www.guavus.com/CubeDefinition" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<!--Fields-->

    <!--Dimension Fields-->

    <tns:RefField FieldName="APP_CATEGORY">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="TT_APP_CAT">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="APP_TYPE">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="GGSN">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="RAT">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="SEGMENT">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="URL_CATEGORY">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="SP">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="DC">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="SGSN">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="CELL_SECTOR">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="APN">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="DEVICE">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="SUBCR">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="APP">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="TT_APP">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="RNC">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>

    <tns:RefField FieldName="ByteArr">
        <tns:String2Id>false</tns:String2Id>
        <tns:Type>ByteArray</tns:Type>
        <tns:DataType>Varbinary</tns:DataType>
        <tns:ColumnWidth>4104</tns:ColumnWidth>
    </tns:RefField>
    <tns:RefField FieldName="LargeByteArr">
        <tns:String2Id>false</tns:String2Id>
        <tns:Type>ByteArray</tns:Type>
        <tns:DataType>Varbinary</tns:DataType>
        <tns:ColumnWidth>2048</tns:ColumnWidth>
    </tns:RefField>
    <tns:RefField FieldName="Source">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="DimensionListContainsSubscriber">
        <tns:String2Id>false</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Int</tns:DataType>
    </tns:RefField>

    <!--Measure Fields-->

    <tns:RefField FieldName="f_PEAK_FLOW_DUR">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_FLOW_DURATION">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_SESSION_DUR">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_FLOW_COUNT">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_UP_BYTES">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_DOWN_BYTES">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_SESSION_COUNT">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_SUBCR_COUNT">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_HIT_COUNT">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_CONC_HIT">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_CONC_SESSION">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_HIT_DURATION">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_PEAK_HIT_DUR">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>
    <tns:RefField FieldName="f_CONC_FLOW">
        <tns:String2Id>true</tns:String2Id>
        <tns:Type>Generic</tns:Type>
        <tns:DataType>Double</tns:DataType>
    </tns:RefField>

    <!--Measures-->
    
    <tns:RefMeasure MeasureName="PEAK_FLOW_DUR">
        <tns:Function>Maximum</tns:Function>
        <tns:Field Field="f_PEAK_FLOW_DUR"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="FLOW_DURATION">
        <tns:Function>Summation</tns:Function>
        <tns:Field Field="f_FLOW_DURATION"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="SESSION_DUR">
        <tns:Function>Summation</tns:Function>
        <tns:Field Field="f_SESSION_DUR"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="FLOW_COUNT">
        <tns:Function>Summation</tns:Function>
        <tns:Field Field="f_FLOW_COUNT"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="UP_BYTES">
        <tns:Function>Summation</tns:Function>
        <tns:Field Field="f_UP_BYTES"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="DOWN_BYTES">
        <tns:Function>Summation</tns:Function>
        <tns:Field Field="f_DOWN_BYTES"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="SESSION_COUNT">
        <tns:Function>Summation</tns:Function>
        <tns:Field Field="f_SESSION_COUNT"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="HIT_COUNT">
        <tns:Function>Summation</tns:Function>
        <tns:Field Field="f_HIT_COUNT"/>
    </tns:RefMeasure>
   
    <tns:RefMeasure MeasureName="PEAK_HIT_DUR">
        <tns:Function>Maximum</tns:Function>
        <tns:Field Field="f_PEAK_HIT_DUR"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="HIT_DURATION">
        <tns:Function>Summation</tns:Function>
        <tns:Field Field="f_HIT_DURATION"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="SUBCR_COUNT">
        <tns:Function>PCSA</tns:Function>
        <tns:StorageMode>MultiPartNonCombinable</tns:StorageMode>
        <tns:Field Field="ByteArr" Persist="true"/>
        <tns:Range Name="PCSA_AllValues" Type="ByteArray" RangeStart="MIN" RangeEnd="MAX"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="CONC_FLOW">
        <tns:Function>CONC</tns:Function>
        <tns:StorageMode>MultiPartNonCombinable</tns:StorageMode>
        <tns:Field Field="LargeByteArr" Persist="true"/>
        <tns:Range Name="PCSA_AllValues" Type="ByteArray" RangeStart="MIN" RangeEnd="MAX"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="CONC_HIT">
        <tns:Function>CONC</tns:Function>
        <tns:StorageMode>MultiPartNonCombinable</tns:StorageMode>
        <tns:Field Field="LargeByteArr" Persist="true"/>
        <tns:Range Name="PCSA_AllValues" Type="ByteArray" RangeStart="MIN" RangeEnd="MAX"/>
    </tns:RefMeasure>

    <tns:RefMeasure MeasureName="CONC_SESSION">
        <tns:Function>CONC</tns:Function>
        <tns:StorageMode>MultiPartNonCombinable</tns:StorageMode>
        <tns:Field Field="LargeByteArr" Persist="true"/>
        <tns:Range Name="PCSA_AllValues" Type="ByteArray" RangeStart="MIN" RangeEnd="MAX"/>
    </tns:RefMeasure>

    <!-- This is a generic PCSA measure -->
    <tns:RefMeasure MeasureName="GenericPCSAMeasure_Example">
        <tns:Function>PCSA</tns:Function>
